export { default as tarifaRoutes } from './tarifaRoutes.js'
export { default as loteRoutes } from './loteRoutes.js'
export { default as reservaRoutes } from './reservaRoutes.js'
export { default as pagoRoutes } from './pagoRoutes.js'
export { default as usuarioRoutes } from './usuarioRoutes.js'
export { default as authRoutes } from './authRoutes.js'